/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manak;

import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Palak
 */
public class donate extends javax.swing.JFrame {

    /**
     * Creates new form donate
     */
    public donate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        itype = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        icond = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        iquant = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DONATE ITEMS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 30, 150, 22);

        itype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itypeActionPerformed(evt);
            }
        });
        getContentPane().add(itype);
        itype.setBounds(170, 80, 80, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENTER ITEM TYPE:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 109, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ITEM QUANTITY:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 98, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ITEM CONDITION:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 160, 104, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("worst = 0 ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 180, 60, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("best = 5");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 180, 48, 16);
        getContentPane().add(icond);
        icond.setBounds(170, 160, 80, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jButton1.setText("CONFIRM DONATION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 240, 153, 25);
        getContentPane().add(iquant);
        iquant.setBounds(170, 120, 80, 22);

        jButton2.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jButton2.setText(" SERVICE?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 10, 93, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palak\\Desktop\\862208.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 410, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String item_type=itype.getText();
        String item_quant=iquant.getText();
        String item_cond=icond.getText();
    
     
            PreparedStatement ps,ps1;
            
            String UserQuery="INSERT INTO `items` (`item_condition`, `item_type`, `item_quantity`) VALUES (?,?,?)";
            String statusquery = "INSERT INTO `donate` (`dstatus`) VALUES (?)";
            
           try {
               ps=My_CNX.getConnection().prepareStatement(UserQuery);
               ps.setString(1,item_cond);
               ps.setString(2,item_type);
               ps.setString(3,item_quant);
               
               ps1=My_CNX.getConnection().prepareStatement(statusquery);
            ps1.setString(1,"pending");
        
               if(ps.executeUpdate()!=0){
                   JOptionPane.showMessageDialog(null,"Check Donation acceptance status");
                   new Menu_Form().setVisible(true);
               this.dispose();
               }
               else{
                   JOptionPane.showMessageDialog(null,"Error:Check Your Information");
                   
               }
           } catch (SQLException ex) {
               Logger.getLogger(usignup.class.getName()).log(Level.SEVERE, null, ex);
           }
               
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        new service().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(donate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(donate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(donate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(donate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new donate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField icond;
    private javax.swing.JTextField iquant;
    private javax.swing.JTextField itype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
