/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manak;

import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Palak
 */
public class service extends javax.swing.JFrame {

    /**
     * Creates new form service
     */
    public service() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        wtype = new javax.swing.JTextField();
        apref = new javax.swing.JTextField();
        wdura = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jButton1.setText("CONFIRM SERVICE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(152, 239, 141, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROVIDE SERVICE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(135, 40, 183, 22);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WORK TYPE:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(139, 94, 74, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AREA PREFERENCE:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(99, 136, 114, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("WORK DURATION (in months):");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(35, 178, 176, 16);

        wtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wtypeActionPerformed(evt);
            }
        });
        getContentPane().add(wtype);
        wtype.setBounds(231, 91, 73, 22);

        apref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprefActionPerformed(evt);
            }
        });
        getContentPane().add(apref);
        apref.setBounds(231, 133, 75, 22);
        getContentPane().add(wdura);
        wdura.setBounds(229, 175, 75, 22);

        jButton2.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jButton2.setText("DONATE?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(323, 13, 87, 25);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palak\\Desktop\\862208.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 430, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wtypeActionPerformed

    private void aprefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aprefActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String work_type=wtype.getText();
        String area_preference=apref.getText();
        String work_duration=wdura.getText();
    
     
            PreparedStatement ps;
            ResultSet rs;
            String registerUserQuery="INSERT INTO `service` (`work_type`, `work_dur`, `area_pref`) VALUES (?,?,?)";
           try {
               ps=My_CNX.getConnection().prepareStatement(registerUserQuery);
               ps.setString(1,work_type);
               ps.setString(2,work_duration);
               ps.setString(3,area_preference);
            
                             
               if(ps.executeUpdate()!=0){
                   JOptionPane.showMessageDialog(null,"Check Service availabilty status");
                   new Menu_Form().setVisible(true);
               this.dispose();
               }
               else{
                   JOptionPane.showMessageDialog(null,"Error:Check Your Information");
                   
               }
           } catch (SQLException ex) {
               Logger.getLogger(usignup.class.getName()).log(Level.SEVERE, null, ex);
           }
        
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new donate().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new service().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apref;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField wdura;
    private javax.swing.JTextField wtype;
    // End of variables declaration//GEN-END:variables
}
