/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manak;

import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class usignup extends javax.swing.JFrame {

    /**
     * Creates new form usignup
     */
    public usignup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ufname = new javax.swing.JTextField();
        ulname = new javax.swing.JTextField();
        uuser = new javax.swing.JTextField();
        uemail = new javax.swing.JTextField();
        uaddress = new javax.swing.JTextField();
        uphone = new javax.swing.JTextField();
        upass = new javax.swing.JPasswordField();
        submit = new javax.swing.JButton();
        gologin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USER SIGNUP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 50, 140, 40);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FIRST NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 130, 72, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LAST NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 160, 67, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USER NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 190, 68, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EMAIL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 220, 35, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ADDRESS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 250, 55, 16);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PHONE NO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 280, 60, 16);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PASSWORD");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 310, 68, 16);
        getContentPane().add(ufname);
        ufname.setBounds(240, 130, 107, 22);
        getContentPane().add(ulname);
        ulname.setBounds(240, 160, 107, 22);
        getContentPane().add(uuser);
        uuser.setBounds(240, 190, 107, 22);

        uemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uemailActionPerformed(evt);
            }
        });
        getContentPane().add(uemail);
        uemail.setBounds(240, 220, 107, 22);

        uaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uaddressActionPerformed(evt);
            }
        });
        getContentPane().add(uaddress);
        uaddress.setBounds(240, 250, 107, 22);

        uphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uphoneActionPerformed(evt);
            }
        });
        getContentPane().add(uphone);
        uphone.setBounds(240, 280, 107, 22);
        getContentPane().add(upass);
        upass.setBounds(240, 310, 107, 22);

        submit.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(60, 380, 77, 25);

        gologin.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        gologin.setText("ALREADY HAVE AN ACCOUNT?");
        gologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gologinActionPerformed(evt);
            }
        });
        getContentPane().add(gologin);
        gologin.setBounds(230, 380, 207, 25);

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jButton1.setText("HOME");
        getContentPane().add(jButton1);
        jButton1.setBounds(12, 23, 67, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Palak\\Desktop\\862208.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, -130, 500, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uemailActionPerformed

    private void uaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uaddressActionPerformed

    private void uphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uphoneActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String fname=ufname.getText();
        String lname=ulname.getText();
        String uname=uuser.getText();
        String pass1=upass.getText();
        String email=uemail.getText();
        String phoneno=uphone.getText();
        String address=uaddress.getText();
        
        
        
        if(!checkUsername(uname))
        {
            PreparedStatement ps;
            ResultSet rs;
            String registerUserQuery="INSERT INTO `user` (`ufname`, `ulname`, `uusername`, `upassword`, `uemail`,`uphone`,`uaddress`) VALUES (?,?,?,?,?,?,?)";
           try {
               ps=My_CNX.getConnection().prepareStatement(registerUserQuery);
               ps.setString(1,fname);
               ps.setString(2,lname);
               ps.setString(3,uname);
               ps.setString(4,pass1);
               ps.setString(5,email);
               ps.setString(6,phoneno);
               ps.setString(7,address);
               
               
               
               if(ps.executeUpdate()!=0){
                   JOptionPane.showMessageDialog(null,"Your Account Has Been Created");
               }
               else{
                   JOptionPane.showMessageDialog(null,"Error:Check Your Information");
                   
               }
           } catch (SQLException ex) {
               Logger.getLogger(usignup.class.getName()).log(Level.SEVERE, null, ex);
           }
            
            
        }
    }//GEN-LAST:event_submitActionPerformed

    private void gologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gologinActionPerformed
        new ulogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gologinActionPerformed

    
    public boolean verifyFields(){
        String fname=ufname.getText();
        String lname=ulname.getText();
        String uname=uuser.getText();
        String pass1=upass.getText();
        String email=uemail.getText();
        String phoneno=uphone.getText();
        String address=uaddress.getText();
        
        if(fname.trim().equals("") || lname.trim().equals("") || uname.trim().equals("")|| pass1.trim().equals("")|| email.trim().equals("")||phoneno.trim().equals("")||address.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null,"One or More Fields Are Empty");
            return false;
        }
        else{
            return true;
            }
     }
     
    public boolean checkUsername(String username){
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist=false;
        
        String query="SELECT * FROM `user` WHERE `uusername` = ?";
        
        try {
            st=My_CNX.getConnection().prepareStatement(query);
            st.setString(1,username);
            rs=st.executeQuery();
            
            if(rs.next()){
                username_exist=true;
                JOptionPane.showMessageDialog(null,"This Username is Already Taken, Choose Another","Username Failed",2);
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(usignup.class.getName()).log(Level.SEVERE, null,ex);
        }
        return username_exist;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gologin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton submit;
    private javax.swing.JTextField uaddress;
    private javax.swing.JTextField uemail;
    private javax.swing.JTextField ufname;
    private javax.swing.JTextField ulname;
    private javax.swing.JPasswordField upass;
    private javax.swing.JTextField uphone;
    private javax.swing.JTextField uuser;
    // End of variables declaration//GEN-END:variables
}
